### ISSUE TITLE
Issue during the execution of pheat2excel_V5.py

### ISSUE THREAD

**Issue by abdeltoure** [fengcong3/HAPPE#2]
Hello, 

I tried to run the script on test data and I get an error linked to the execution of pheat2excel_V5.py.
You can find the error log down below.
I would also like to know if it is possible to have access to your publication data to be sure that any problem is not data related.

Best regards,
Abdel

****Traceback (most recent call last):  File "/home/s953680/apps/python/current/lib/python3.8/site-packages/openpyxl-3.2.0b1-py3.8.egg/openpyxl/utils/cell.py", line 110, in get_column_letter    return _STRING_COL_CACHE[idx]
KeyError: 18279

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/home/s953680/apps/python/3.8/lib/python3.8/site-packages/HAPPE-0.1.4-py3.8.egg/HAPPE/pheat2excel_V5.py", line 225, in <module>    col_let = get_column_letter(start_col+index+2)  File "/home/s953680/apps/python/current/lib/python3.8/site-packages/openpyxl-3.2.0b1-py3.8.egg/openpyxl/utils/cell.py", line 112, in get_column_letter    raise ValueError("Invalid column index {0}".format(idx))
ValueError: Invalid column index 18279
[2022-09-06 16:29:36,947] - HAPPE - ERROR - add heat matrix -- retrun code:256
 like 1****

**Comment by fengcong3** [comment]
Hi,

This is an error from openpyxl, which only supports excel sheet with a maximum of 18,278 columns. You can eliminate this error by reducing SNP/INDEL site.

I've uploaded the example data covered in the publication as well as the shell scripts, which are in the `example/` folder.

Hope this solves your problem!

Best,
Cong Feng

**Comment by fengcong3** [comment]
I'm gonna close this issue, if you have more question, please feel free to reopen it.
